version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}-nginx
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html
      - ./infrastructure/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel
  mariadb:
    image: mariadb:latest
    container_name: ${APP_NAME}-mariadb
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - laravel
    ports:
      - '3306:3306'

  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    restart: always
    ports:
      - 8090:80
    volumes:
      - /sessions
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - laravel

  redis:
    container_name: ${APP_NAME}-redis
    image: redis:latest
    ports:
      - "6379:6379"

  php:
    build:
      context: .
      dockerfile: ./infrastructure/docker/php/Dockerfile
    container_name: ${APP_NAME}-php
    environment:
      - "ENV_SUBSTITUTION_ENABLE=true"
      - "PHP_MEMORY_LIMIT=512M"
      - "PHP_FPM_LISTEN=9000"
      - "PHP_SESSION_GC_MAXLIFETIME=7200"
      - "XDEBUG_MODE=debug"
    expose:
      - "9000"
    volumes:
      - ./:/var/www/html
      - ./infrastructure/docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - mariadb
    links:
      - mariadb
    networks:
      - laravel

  npm:
    image: node:13.7
    container_name: ${APP_NAME}-npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  ngrok:
    image: shkoliar/ngrok:latest
    container_name: ${APP_NAME}-ngrok
    ports:
      - 4551:4551
    links:
      - nginx
    environment:
      - DOMAIN=nginx
      - PORT=80
    networks:
      - laravel
